### ISSUE TITLE
May Tent use any Git repo or just Github?

### ISSUE THREAD

**Issue by ventolinmx** [securityfirst/tent#12]

**Comment by Coccodrillo** [comment]
Hi @ventolinmono, at this moment the api for editing is supporting only Github, due to limited time and resources, we have only implemented for it. From the quick glance at [GitLab docs](https://docs.gitlab.com/ee/api/oauth2.html#gitlab-as-an-oauth2-provider), support for that platform would be easy to add. All of the other methods would work with any public repo and in fact we are preparing a version of Umbrella app that consumes content directly from the repo.
